# SPDX-FileCopyrightText: © 2026 Rafael V. Volkmer <rafael.v.volkmer@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

[files]
extend-exclude = [
  ".git/**",
  "LICENSES/**",
  "**/*.svg",
  "**/*.aff",
  "**/*.dic",
  "**/*.lock",
  "**/*.min.*",
  "**/*.patch",
  "tests/mock/git_hooks/coil-hook-test-suite.lua",
]

[default]
locale = "en-us"
check-filename = true
check-file = true
unicode = true

[default.extend-words]
# BEGIN GENERATED WORDS
"ABA" = "ABA"
"ABI" = "ABI"
"abidiff" = "abidiff"
"accessor" = "accessor"
"accessors" = "accessors"
"Acked" = "Acked"
"actionlint" = "actionlint"
"addressability" = "addressability"
"alignas" = "alignas"
"alignof" = "alignof"
"Allman" = "Allman"
"alloca" = "alloca"
"allocator's" = "allocator's"
"allowlist" = "allowlist"
"allowlisted" = "allowlisted"
"allowlists" = "allowlists"
"analyzability" = "analyzability"
"ANSI" = "ANSI"
"API" = "API"
"APIs" = "APIs"
"archiver" = "archiver"
"argv" = "argv"
"ASan" = "ASan"
"ASCII" = "ASCII"
"asctime" = "asctime"
"Assisted" = "Assisted"
"atof" = "atof"
"atoi" = "atoi"
"atol" = "atol"
"backpressure" = "backpressure"
"BANNED" = "BANNED"
"Bazel" = "Bazel"
"bazelrc" = "bazelrc"
"bcmp" = "bcmp"
"bcopy" = "bcopy"
"benchmarked" = "benchmarked"
"bidi" = "bidi"
"binutils" = "binutils"
"bitfield" = "bitfield"
"bitmask" = "bitmask"
"bitmasks" = "bitmasks"
"bitwise" = "bitwise"
"boolean" = "boolean"
"booleans" = "booleans"
"BTB" = "BTB"
"buffer_t" = "buffer_t"
"bugprone" = "bugprone"
"buildable" = "buildable"
"builtins" = "builtins"
"bytewise" = "bytewise"
"bzero" = "bzero"
"Böhm" = "Böhm"
"C23" = "C23"
"C28719" = "C28719"
"cachetlb" = "cachetlb"
"callee" = "callee"
"callees" = "callees"
"calloc" = "calloc"
"canonicalization" = "canonicalization"
"canonicalize" = "canonicalize"
"Canonicalizing" = "Canonicalizing"
"CAPEC" = "CAPEC"
"CBAN" = "CBAN"
"CERT" = "CERT"
"chdir" = "chdir"
"checkasm" = "checkasm"
"checkpatch" = "checkpatch"
"checkstack" = "checkstack"
"CI" = "CI"
"CICD" = "CICD"
"CISA" = "CISA"
"CLI" = "CLI"
"CLOEXEC" = "CLOEXEC"
"CMake" = "CMake"
"cmov" = "cmov"
"codec" = "codec"
"codegen" = "codegen"
"codespell" = "codespell"
"codespellrc" = "codespellrc"
"Coil" = "Coil"
"CoilStr" = "CoilStr"
"config" = "config"
"Const" = "Const"
"constness" = "constness"
"copyable" = "copyable"
"CPERF" = "CPERF"
"CPIT" = "CPIT"
"CPU" = "CPU"
"CPUs" = "CPUs"
"CPython" = "CPython"
"CPython's" = "CPython's"
"crypto" = "crypto"
"CSpell" = "CSpell"
"CSS" = "CSS"
"CSTYLE" = "CSTYLE"
"ctest" = "ctest"
"ctype" = "ctype"
"CVEs" = "CVEs"
"CWE" = "CWE"
"cybersecurity" = "cybersecurity"
"Cyclomatic" = "Cyclomatic"
"DCMAKE" = "DCMAKE"
"DCO" = "DCO"
"DDIO" = "DDIO"
"deallocation" = "deallocation"
"declarator" = "declarator"
"declarators" = "declarators"
"declspec" = "declspec"
"deinit" = "deinit"
"denylist" = "denylist"
"dereference" = "dereference"
"dereferenced" = "dereferenced"
"dereferences" = "dereferences"
"dereferencing" = "dereferencing"
"deregistering" = "deregistering"
"deregisters" = "deregisters"
"deregistration" = "deregistration"
"deserialization" = "deserialization"
"deserialize" = "deserialize"
"destructors" = "destructors"
"devirtualize" = "devirtualize"
"disambiguator" = "disambiguator"
"DLL" = "DLL"
"dllexport" = "dllexport"
"dllimport" = "dllimport"
"DLLs" = "DLLs"
"dlopen" = "dlopen"
"DMA" = "DMA"
"DO" = "DO"
"DOI" = "DOI"
"DPDK" = "DPDK"
"DPROJECT" = "DPROJECT"
"drand" = "drand"
"DSAMPLE" = "DSAMPLE"
"DSB" = "DSB"
"DTLB" = "DTLB"
"DTOs" = "DTOs"
"dtos" = "dtos"
"EACCES" = "EACCES"
"EditorConfig" = "EditorConfig"
"EEPROM" = "EEPROM"
"EFAULT" = "EFAULT"
"EINTR" = "EINTR"
"EINVAL" = "EINVAL"
"ELF" = "ELF"
"elidable" = "elidable"
"elif" = "elif"
"endforeach" = "endforeach"
"endian" = "endian"
"endianness" = "endianness"
"ENOENT" = "ENOENT"
"ENOMEM" = "ENOMEM"
"ENOSPC" = "ENOSPC"
"ENOTSUP" = "ENOTSUP"
"enum" = "enum"
"enums" = "enums"
"envp" = "envp"
"EOF" = "EOF"
"EOVERFLOW" = "EOVERFLOW"
"ERANGE" = "ERANGE"
"errno" = "errno"
"execlp" = "execlp"
"execve" = "execve"
"execvp" = "execvp"
"failpoint" = "failpoint"
"fallthrough" = "fallthrough"
"fcntl" = "fcntl"
"Ferrante" = "Ferrante"
"FFI" = "FFI"
"FFmpeg" = "FFmpeg"
"FFmpeg's" = "FFmpeg's"
"fieldwise" = "fieldwise"
"fixup" = "fixup"
"Follows" = "Follows"
"fopen" = "fopen"
"foreach" = "foreach"
"Forgejo" = "Forgejo"
"FP" = "FP"
"fprintf" = "fprintf"
"Frama" = "Frama"
"fread" = "fread"
"fsanitize" = "fsanitize"
"fscanf" = "fscanf"
"fstack" = "fstack"
"fullpath" = "fullpath"
"futex" = "futex"
"fuzzer" = "fuzzer"
"fuzzers" = "fuzzers"
"fwrite" = "fwrite"
"GC" = "GC"
"GDB" = "GDB"
"getenv" = "getenv"
"GETFD" = "GETFD"
"getts" = "getts"
"GitHub" = "GitHub"
"globals" = "globals"
"gmtime" = "gmtime"
"GNU" = "GNU"
"GNUC" = "GNUC"
"GPU" = "GPU"
"growable" = "growable"
"gRPC" = "gRPC"
"grpcs" = "grpcs"
"GUIs" = "GUIs"
"HAProxy" = "HAProxy"
"Hardcoded" = "Hardcoded"
"hoc" = "hoc"
"hostname" = "hostname"
"hotspot" = "hotspot"
"HTML" = "HTML"
"HTTP" = "HTTP"
"HTTPS" = "HTTPS"
"ID" = "ID"
"IDE" = "IDE"
"idempotence" = "idempotence"
"idempotency" = "idempotency"
"IDs" = "IDs"
"IEC" = "IEC"
"IEEE" = "IEEE"
"ifdef" = "ifdef"
"ifndef" = "ifndef"
"initializer" = "initializer"
"initializers" = "initializers"
"inlined" = "inlined"
"inlining" = "inlining"
"intptr" = "intptr"
"intrinsics" = "intrinsics"
"IPC" = "IPC"
"isalpha" = "isalpha"
"isdigit" = "isdigit"
"isfinite" = "isfinite"
"isnan" = "isnan"
"ISO" = "ISO"
"ISR" = "ISR"
"itoa" = "itoa"
"Jacopini" = "Jacopini"
"Jacopini's" = "Jacopini's"
"JITs" = "JITs"
"JPL" = "JPL"
"JSON" = "JSON"
"JSONC" = "JSONC"
"Kernighan" = "Kernighan"
"Klocwork" = "Klocwork"
"kref" = "kref"
"lcore" = "lcore"
"libabigail" = "libabigail"
"libc" = "libc"
"libdevice" = "libdevice"
"libmemalloc" = "libmemalloc"
"LLVM" = "LLVM"
"LLVM's" = "LLVM's"
"localtime" = "localtime"
"lockless" = "lockless"
"longjmp" = "longjmp"
"lookups" = "lookups"
"loopback" = "loopback"
"LRU" = "LRU"
"lstrcat" = "lstrcat"
"lstrcpy" = "lstrcpy"
"ltoa" = "ltoa"
"Lua" = "Lua"
"lvalue" = "lvalue"
"lychee" = "lychee"
"MAC" = "MAC"
"makepath" = "makepath"
"malloc" = "malloc"
"markdownlint" = "markdownlint"
"mbscat" = "mbscat"
"mbscpy" = "mbscpy"
"mbsncpy" = "mbsncpy"
"memcmp" = "memcmp"
"memcpy" = "memcpy"
"memmove" = "memmove"
"memset" = "memset"
"memset_explicit" = "memset_explicit"
"memzero" = "memzero"
"metacharacters" = "metacharacters"
"microarchitectural" = "microarchitectural"
"microarchitecture" = "microarchitecture"
"mimalloc" = "mimalloc"
"miscompilation" = "miscompilation"
"misconfiguration" = "misconfiguration"
"MisExpect" = "MisExpect"
"misprediction" = "misprediction"
"MISRA" = "MISRA"
"mitigations" = "mitigations"
"MITRE" = "MITRE"
"mktemp" = "mktemp"
"mlockall" = "mlockall"
"MMIO" = "MMIO"
"modelines" = "modelines"
"MSHR" = "MSHR"
"multibyte" = "multibyte"
"multicast" = "multicast"
"multiline" = "multiline"
"multithreaded" = "multithreaded"
"multithreading" = "multithreading"
"mutex" = "mutex"
"mutexes" = "mutexes"
"namespace" = "namespace"
"namespaced" = "namespaced"
"namespaces" = "namespaces"
"NASA" = "NASA"
"NDEBUG" = "NDEBUG"
"nginx" = "nginx"
"nginx's" = "nginx's"
"no-stdlib" = "no-stdlib"
"noexecstack" = "noexecstack"
"NOLINTNEXTLINE" = "NOLINTNEXTLINE"
"nonces" = "nonces"
"nonliteral" = "nonliteral"
"nonlocal" = "nonlocal"
"nonlocally" = "nonlocally"
"Nonrepresentative" = "Nonrepresentative"
"nonterminated" = "nonterminated"
"npm" = "npm"
"NUL" = "NUL"
"NULL" = "NULL"
"nullability" = "nullability"
"nullable" = "nullable"
"Nulling" = "Nulling"
"NUMA" = "NUMA"
"NVM" = "NVM"
"NVMe" = "NVMe"
"OCI" = "OCI"
"offsetof" = "offsetof"
"OOM" = "OOM"
"OpenPGP" = "OpenPGP"
"OpenSSF" = "OpenSSF"
"OpenTitan" = "OpenTitan"
"optimizer's" = "optimizer's"
"Ottenstein" = "Ottenstein"
"pahole" = "pahole"
"parameterization" = "parameterization"
"PCIe" = "PCIe"
"PDG" = "PDG"
"perror" = "perror"
"PII" = "PII"
"PMU" = "PMU"
"pointee" = "pointee"
"popen" = "popen"
"POSIX" = "POSIX"
"postconditions" = "postconditions"
"pragma" = "pragma"
"pragmas" = "pragmas"
"preallocated" = "preallocated"
"preallocation" = "preallocation"
"prefault" = "prefault"
"prefetch" = "prefetch"
"prefetched" = "prefetched"
"prefetcher" = "prefetcher"
"prefetchers" = "prefetchers"
"Prefetching" = "Prefetching"
"preprocessor" = "preprocessor"
"PRNG" = "PRNG"
"PRNGs" = "PRNGs"
"profiler" = "profiler"
"pthread" = "pthread"
"ptrdiff" = "ptrdiff"
"putenv" = "putenv"
"QEMU" = "QEMU"
"qsort" = "qsort"
"RAM" = "RAM"
"RCU" = "RCU"
"RCU's" = "RCU's"
"RDONLY" = "RDONLY"
"reachability" = "reachability"
"README" = "README"
"reallocations" = "reallocations"
"realpath" = "realpath"
"Redpanda" = "Redpanda"
"Redpanda's" = "Redpanda's"
"reentrancy" = "reentrancy"
"reentrant" = "reentrant"
"refcount" = "refcount"
"refcounts" = "refcounts"
"Refs" = "Refs"
"reimplementing" = "reimplementing"
"rejectable" = "rejectable"
"relocations" = "relocations"
"RELRO" = "RELRO"
"replayable" = "replayable"
"Reported" = "Reported"
"representability" = "representability"
"requeue" = "requeue"
"reusability" = "reusability"
"Reviewed" = "Reviewed"
"Ritchie" = "Ritchie"
"RNG" = "RNG"
"ROM" = "ROM"
"RSB" = "RSB"
"RTLD" = "RTLD"
"runtime's" = "runtime's"
"runtimes" = "runtimes"
"rwlock" = "rwlock"
"safepoint" = "safepoint"
"SAST" = "SAST"
"scanf" = "scanf"
"SDL" = "SDL"
"searchability" = "searchability"
"SEI" = "SEI"
"seqcount" = "seqcount"
"serializer" = "serializer"
"SESE" = "SESE"
"SETFD" = "SETFD"
"setjmp" = "setjmp"
"shootdown" = "shootdown"
"shootdowns" = "shootdowns"
"SI" = "SI"
"Signed" = "Signed"
"signedness" = "signedness"
"SIMD" = "SIMD"
"SPDX" = "SPDX"
"splitpath" = "splitpath"
"SQL" = "SQL"
"Squid" = "Squid"
"srand" = "srand"
"sscanf" = "sscanf"
"SSDF" = "SSDF"
"SSRF" = "SSRF"
"stdalign" = "stdalign"
"stdatomic" = "stdatomic"
"stdckdint" = "stdckdint"
"stdint" = "stdint"
"stdio" = "stdio"
"stdlib" = "stdlib"
"strcat" = "strcat"
"StrCpy" = "StrCpy"
"strcpy" = "strcpy"
"STREQUAL" = "STREQUAL"
"strerror" = "strerror"
"Stringification" = "Stringification"
"strncat" = "strncat"
"strncpy" = "strncpy"
"strsep" = "strsep"
"strtok" = "strtok"
"strtol" = "strtol"
"subobject" = "subobject"
"Suggested" = "Suggested"
"suppressions" = "suppressions"
"SV" = "SV"
"swprintf" = "swprintf"
"systemd" = "systemd"
"Taplo" = "Taplo"
"TCHAR" = "TCHAR"
"tcscat" = "tcscat"
"tcscpy" = "tcscpy"
"tcsncpy" = "tcsncpy"
"teardown" = "teardown"
"tempnam" = "tempnam"
"Tested" = "Tested"
"TLB" = "TLB"
"TLS" = "TLS"
"tmpnam" = "tmpnam"
"tolower" = "tolower"
"TOML" = "TOML"
"toolchain" = "toolchain"
"toolchains" = "toolchains"
"toupper" = "toupper"
"transactionally" = "transactionally"
"TS" = "TS"
"typedef" = "typedef"
"typedefs" = "typedefs"
"typos" = "typos"
"UB" = "UB"
"UBSan" = "UBSan"
"uintptr" = "uintptr"
"ultoa" = "ultoa"
"unary" = "unary"
"uncommented" = "uncommented"
"uncontended" = "uncontended"
"unmapping" = "unmapping"
"unqual" = "unqual"
"unregister" = "unregister"
"unreviewed" = "unreviewed"
"Unsequenced" = "Unsequenced"
"unsetenv" = "unsetenv"
"unstripped" = "unstripped"
"unsynchronized" = "unsynchronized"
"untracked" = "untracked"
"untrusted" = "untrusted"
"unvalidated" = "unvalidated"
"unversioned" = "unversioned"
"URI" = "URI"
"URL" = "URL"
"UTF" = "UTF"
"Vale" = "Vale"
"validator" = "validator"
"variadic" = "variadic"
"vendored" = "vendored"
"vfscanf" = "vfscanf"
"VLA" = "VLA"
"VLAs" = "VLAs"
"Volkmer" = "Volkmer"
"vscanf" = "vscanf"
"vsnprintf" = "vsnprintf"
"vsprintf" = "vsprintf"
"vsscanf" = "vsscanf"
"vSwitch" = "vSwitch"
"wakeup" = "wakeup"
"wakeups" = "wakeups"
"Wbidi" = "Wbidi"
"WCET" = "WCET"
"wchar" = "wchar"
"Wconversion" = "Wconversion"
"wcscat" = "wcscat"
"wcscpy" = "wcscpy"
"wcslen" = "wcslen"
"wcsncat" = "wcsncat"
"wcsncpy" = "wcsncpy"
"Wdeclaration" = "Wdeclaration"
"Werror" = "Werror"
"Wextra" = "Wextra"
"Wformat" = "Wformat"
"Wireshark" = "Wireshark"
"Wireshark's" = "Wireshark's"
"wmem" = "wmem"
"Wmissing" = "Wmissing"
"worklist" = "worklist"
"Wpedantic" = "Wpedantic"
"writability" = "writability"
"writeback" = "writeback"
"Wshadow" = "Wshadow"
"Wsign" = "Wsign"
"wsprintf" = "wsprintf"
"Wstrict" = "Wstrict"
"Wundef" = "Wundef"
"Wvla" = "Wvla"
"wvsprintf" = "wvsprintf"
"xffffffffu" = "xffffffffu"
"XML" = "XML"
"XOR" = "XOR"
"XSS" = "XSS"
"XXE" = "XXE"
"YAML" = "YAML"
"yamllint" = "yamllint"
"Zizmor" = "Zizmor"
"zstd" = "zstd"
# END GENERATED WORDS

[default.extend-identifiers]
"MisExpect" = "MisExpect"
"StrCpy" = "StrCpy"

# EOF
