# SPDX-FileCopyrightText: © 2026 Rafael V. Volkmer <rafael.v.volkmer@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

[files]
extend-exclude = [
  ".git/**",
  "LICENSES/**",
  "**/*.svg",
  "**/*.aff",
  "**/*.dic",
  "**/*.lock",
  "**/*.min.*",
  "**/*.patch",
  "tests/mock/git_hooks/coil-hook-test-suite.lua",
]

[default]
locale = "en-us"
check-filename = true
check-file = true
unicode = true

[default.extend-words]
# BEGIN GENERATED WORDS
"ABA" = "ABA"
"ABI" = "ABI"
"accessors" = "accessors"
"Acked" = "Acked"
"actionlint" = "actionlint"
"Allman" = "Allman"
"alloca" = "alloca"
"allowlist" = "allowlist"
"allowlisted" = "allowlisted"
"analyzability" = "analyzability"
"ANSI" = "ANSI"
"API" = "API"
"APIs" = "APIs"
"argv" = "argv"
"ASCII" = "ASCII"
"asctime" = "asctime"
"Assisted" = "Assisted"
"atof" = "atof"
"atoi" = "atoi"
"atol" = "atol"
"BANNED" = "BANNED"
"Bazel" = "Bazel"
"bazelrc" = "bazelrc"
"bcmp" = "bcmp"
"bcopy" = "bcopy"
"bitwise" = "bitwise"
"boolean" = "boolean"
"booleans" = "booleans"
"builtins" = "builtins"
"bzero" = "bzero"
"Böhm" = "Böhm"
"C23" = "C23"
"C28719" = "C28719"
"callee" = "callee"
"calloc" = "calloc"
"canonicalization" = "canonicalization"
"canonicalize" = "canonicalize"
"CAPEC" = "CAPEC"
"CBAN" = "CBAN"
"CERT" = "CERT"
"chdir" = "chdir"
"CI" = "CI"
"CISA" = "CISA"
"CLI" = "CLI"
"CMake" = "CMake"
"codespell" = "codespell"
"codespellrc" = "codespellrc"
"Coil" = "Coil"
"CoilStr" = "CoilStr"
"config" = "config"
"Const" = "Const"
"CPIT" = "CPIT"
"CPU" = "CPU"
"CPUs" = "CPUs"
"crypto" = "crypto"
"CSpell" = "CSpell"
"CSS" = "CSS"
"CSTYLE" = "CSTYLE"
"ctype" = "ctype"
"CVEs" = "CVEs"
"CWE" = "CWE"
"cybersecurity" = "cybersecurity"
"Cyclomatic" = "Cyclomatic"
"DCO" = "DCO"
"deallocation" = "deallocation"
"denylist" = "denylist"
"dereference" = "dereference"
"dereferenced" = "dereferenced"
"dereferencing" = "dereferencing"
"deregistering" = "deregistering"
"deregisters" = "deregisters"
"deregistration" = "deregistration"
"deserialization" = "deserialization"
"deserialize" = "deserialize"
"dlopen" = "dlopen"
"DMA" = "DMA"
"DO" = "DO"
"DOI" = "DOI"
"drand" = "drand"
"DTOs" = "DTOs"
"dtos" = "dtos"
"EditorConfig" = "EditorConfig"
"EEPROM" = "EEPROM"
"EFAULT" = "EFAULT"
"EINVAL" = "EINVAL"
"ELF" = "ELF"
"elif" = "elif"
"endianness" = "endianness"
"ENOMEM" = "ENOMEM"
"ENOSPC" = "ENOSPC"
"enum" = "enum"
"enums" = "enums"
"EOF" = "EOF"
"ERANGE" = "ERANGE"
"errno" = "errno"
"execlp" = "execlp"
"execvp" = "execvp"
"fallthrough" = "fallthrough"
"Ferrante" = "Ferrante"
"FFI" = "FFI"
"Follows" = "Follows"
"fopen" = "fopen"
"Forgejo" = "Forgejo"
"FP" = "FP"
"fprintf" = "fprintf"
"Frama" = "Frama"
"fread" = "fread"
"fscanf" = "fscanf"
"fullpath" = "fullpath"
"fuzzer" = "fuzzer"
"fuzzers" = "fuzzers"
"fwrite" = "fwrite"
"GC" = "GC"
"GDB" = "GDB"
"getenv" = "getenv"
"getts" = "getts"
"GitHub" = "GitHub"
"gmtime" = "gmtime"
"GNU" = "GNU"
"GPU" = "GPU"
"gRPC" = "gRPC"
"grpcs" = "grpcs"
"Hardcoded" = "Hardcoded"
"hoc" = "hoc"
"hostname" = "hostname"
"HTML" = "HTML"
"HTTP" = "HTTP"
"HTTPS" = "HTTPS"
"ID" = "ID"
"IDE" = "IDE"
"IDs" = "IDs"
"IEC" = "IEC"
"IEEE" = "IEEE"
"ifdef" = "ifdef"
"ifndef" = "ifndef"
"initializers" = "initializers"
"intptr" = "intptr"
"IPC" = "IPC"
"isalpha" = "isalpha"
"isdigit" = "isdigit"
"ISO" = "ISO"
"ISR" = "ISR"
"itoa" = "itoa"
"Jacopini" = "Jacopini"
"Jacopini's" = "Jacopini's"
"JITs" = "JITs"
"JPL" = "JPL"
"JSON" = "JSON"
"JSONC" = "JSONC"
"Kernighan" = "Kernighan"
"Klocwork" = "Klocwork"
"libc" = "libc"
"libmemalloc" = "libmemalloc"
"localtime" = "localtime"
"longjmp" = "longjmp"
"lookups" = "lookups"
"loopback" = "loopback"
"LRU" = "LRU"
"lstrcat" = "lstrcat"
"lstrcpy" = "lstrcpy"
"ltoa" = "ltoa"
"lvalue" = "lvalue"
"lychee" = "lychee"
"MAC" = "MAC"
"makepath" = "makepath"
"malloc" = "malloc"
"markdownlint" = "markdownlint"
"mbscat" = "mbscat"
"mbscpy" = "mbscpy"
"mbsncpy" = "mbsncpy"
"memcmp" = "memcmp"
"memcpy" = "memcpy"
"memmove" = "memmove"
"memset" = "memset"
"miscompilation" = "miscompilation"
"misconfiguration" = "misconfiguration"
"MISRA" = "MISRA"
"MITRE" = "MITRE"
"mktemp" = "mktemp"
"MMIO" = "MMIO"
"multibyte" = "multibyte"
"multicast" = "multicast"
"multithreaded" = "multithreaded"
"mutex" = "mutex"
"mutexes" = "mutexes"
"namespace" = "namespace"
"namespaced" = "namespaced"
"namespaces" = "namespaces"
"NASA" = "NASA"
"no-stdlib" = "no-stdlib"
"nonces" = "nonces"
"nonliteral" = "nonliteral"
"nonlocal" = "nonlocal"
"NUL" = "NUL"
"NULL" = "NULL"
"nullability" = "nullability"
"nullable" = "nullable"
"NVM" = "NVM"
"NVMe" = "NVMe"
"OCI" = "OCI"
"OOM" = "OOM"
"OpenPGP" = "OpenPGP"
"Ottenstein" = "Ottenstein"
"parameterization" = "parameterization"
"PDG" = "PDG"
"perror" = "perror"
"PII" = "PII"
"popen" = "popen"
"POSIX" = "POSIX"
"preallocated" = "preallocated"
"preallocation" = "preallocation"
"preprocessor" = "preprocessor"
"PRNGs" = "PRNGs"
"pthread" = "pthread"
"ptrdiff" = "ptrdiff"
"putenv" = "putenv"
"qsort" = "qsort"
"RAM" = "RAM"
"reachability" = "reachability"
"README" = "README"
"realpath" = "realpath"
"reentrancy" = "reentrancy"
"reentrant" = "reentrant"
"refcount" = "refcount"
"refcounts" = "refcounts"
"Refs" = "Refs"
"reimplementing" = "reimplementing"
"Reported" = "Reported"
"reusability" = "reusability"
"Reviewed" = "Reviewed"
"Ritchie" = "Ritchie"
"RNG" = "RNG"
"ROM" = "ROM"
"RTLD" = "RTLD"
"runtimes" = "runtimes"
"SAST" = "SAST"
"scanf" = "scanf"
"SDL" = "SDL"
"SEI" = "SEI"
"SESE" = "SESE"
"setjmp" = "setjmp"
"SI" = "SI"
"Signed" = "Signed"
"SIMD" = "SIMD"
"SPDX" = "SPDX"
"splitpath" = "splitpath"
"SQL" = "SQL"
"Squid" = "Squid"
"srand" = "srand"
"sscanf" = "sscanf"
"stdint" = "stdint"
"stdio" = "stdio"
"stdlib" = "stdlib"
"strcat" = "strcat"
"StrCpy" = "StrCpy"
"strcpy" = "strcpy"
"strerror" = "strerror"
"Stringification" = "Stringification"
"strncat" = "strncat"
"strncpy" = "strncpy"
"strsep" = "strsep"
"strtok" = "strtok"
"strtol" = "strtol"
"subobject" = "subobject"
"Suggested" = "Suggested"
"suppressions" = "suppressions"
"SV" = "SV"
"swprintf" = "swprintf"
"Taplo" = "Taplo"
"TCHAR" = "TCHAR"
"tcscat" = "tcscat"
"tcscpy" = "tcscpy"
"tcsncpy" = "tcsncpy"
"tempnam" = "tempnam"
"Tested" = "Tested"
"TLS" = "TLS"
"tmpnam" = "tmpnam"
"tolower" = "tolower"
"TOML" = "TOML"
"toupper" = "toupper"
"TS" = "TS"
"typedefs" = "typedefs"
"typos" = "typos"
"UB" = "UB"
"uintptr" = "uintptr"
"ultoa" = "ultoa"
"unreviewed" = "unreviewed"
"Unsequenced" = "Unsequenced"
"unsetenv" = "unsetenv"
"unsynchronized" = "unsynchronized"
"untracked" = "untracked"
"untrusted" = "untrusted"
"unvalidated" = "unvalidated"
"URI" = "URI"
"URL" = "URL"
"UTF" = "UTF"
"Vale" = "Vale"
"variadic" = "variadic"
"vfscanf" = "vfscanf"
"VLA" = "VLA"
"VLAs" = "VLAs"
"Volkmer" = "Volkmer"
"vscanf" = "vscanf"
"vsnprintf" = "vsnprintf"
"vsprintf" = "vsprintf"
"vsscanf" = "vsscanf"
"wakeup" = "wakeup"
"wcscat" = "wcscat"
"wcscpy" = "wcscpy"
"wcslen" = "wcslen"
"wcsncat" = "wcsncat"
"wcsncpy" = "wcsncpy"
"wsprintf" = "wsprintf"
"wvsprintf" = "wvsprintf"
"xffffffffu" = "xffffffffu"
"XML" = "XML"
"XOR" = "XOR"
"YAML" = "YAML"
"yamllint" = "yamllint"
"zstd" = "zstd"
# END GENERATED WORDS

[default.extend-identifiers]
"StrCpy" = "StrCpy"

# EOF
