# SPDX-FileCopyrightText: © 2026 Rafael V. Volkmer <rafael.v.volkmer@gmail.com>
# SPDX-License-Identifier: GPL-3.0-only

StylesPath = styles
MinAlertLevel = suggestion
Vocab = Coil

[formats]
mdx = md

[*.{md,markdown,mdx,rst,adoc}]
BasedOnStyles = Coil
Coil.Anthropomorphism = warning
Coil.PassiveVoice = error
Coil.PercentSpacing = NO
Coil.SecondPerson = NO

[docs/code_style/c_language/**]
BasedOnStyles = CoilSpelling
Coil = NO
Coil.Anthropomorphism = NO
Coil.PassiveVoice = NO
Coil.PercentSpacing = NO
Coil.SecondPerson = NO

[*.paper.{md,markdown,mdx,rst,adoc}]
BasedOnStyles = Coil
Coil.Anthropomorphism = error
Coil.PassiveVoice = error
Coil.PercentSpacing = error
Coil.ReaderAddress = NO
Coil.SecondPerson = warning

[docs/articles/**]
BasedOnStyles = Coil
Coil.Anthropomorphism = error
Coil.PassiveVoice = error
Coil.PercentSpacing = error
Coil.ReaderAddress = NO
Coil.SecondPerson = warning

[docs/papers/**]
BasedOnStyles = Coil
Coil.Anthropomorphism = error
Coil.PassiveVoice = error
Coil.PercentSpacing = error
Coil.ReaderAddress = NO
Coil.SecondPerson = warning

[docs/research/**]
BasedOnStyles = Coil
Coil.Anthropomorphism = error
Coil.PassiveVoice = error
Coil.PercentSpacing = error
Coil.ReaderAddress = NO
Coil.SecondPerson = warning

[*.{c,h,cpp,hpp}]
BasedOnStyles = Coil
Coil.Acronyms = NO
Coil.LongSentence = NO
Coil.PercentSpacing = NO
Coil.SecondPerson = NO

# EOF
